import type {
  ActivityNote,
  AthleteConfig,
  DailyNote,
  ManualActivity,
} from "../types";

export const demoAthleteConfig: AthleteConfig = {
  athleteName: "Sample Runner",
  race: {
    name: "Example City Marathon",
    date: "2026-11-29",
    goalTime: "4:30 stretch goal",
    goalPace: "10:18 min/mi",
  },
  background: {
    experienceLevel: "beginner",
    runningBackground:
      "Sample Runner is building consistency with easy run-walk training and conservative mileage increases.",
    baselineRun: {
      date: "2026-06-01",
      distanceMiles: 3.1,
      durationMinutes: 36,
      notes: "Comfortable fake baseline effort on a flat demo route.",
    },
    travelNoRunningBreak: {
      startDate: "2026-07-06",
      endDate: "2026-07-10",
      notes: "Fake planned travel week with walking only.",
    },
  },
  normalLifestyleActivity: {
    averageDailySteps: 8500,
    notes: "Moderate fake walking during a normal demo week.",
  },
  recurringCrossTraining: [
    {
      activityType: "mobility",
      frequency: "2 times per week",
      notes: "Light fake mobility routine.",
    },
    {
      activityType: "weights",
      frequency: "1 time per week",
      notes: "Short fake full-body strength session.",
    },
  ],
  unitPreferences: {
    distance: "miles",
    pace: "minutes_per_mile",
    duration: "minutes",
  },
};

export const demoDailyNotes: DailyNote[] = [
  dailyNote("2026-06-22", 8200, 1, 0, "none", "none", false, 2, 8, 8, 3, 8),
  dailyNote(
    "2026-06-23",
    9400,
    2,
    1,
    "right knee",
    "dull",
    false,
    3,
    7,
    7,
    4,
    8,
  ),
  dailyNote("2026-06-24", 7600, 2, 0, "none", "none", false, 3, 7, 8, 3, 7),
  dailyNote("2026-06-25", 8800, 3, 0, "none", "none", false, 4, 7, 7, 4, 8),
  dailyNote(
    "2026-06-26",
    11200,
    3,
    2,
    "left calf",
    "tight",
    false,
    4,
    6,
    7,
    5,
    7,
  ),
  dailyNote(
    "2026-06-27",
    9000,
    2,
    1,
    "left calf",
    "tight",
    false,
    3,
    7,
    8,
    3,
    8,
  ),
  dailyNote("2026-06-28", 7000, 1, 0, "none", "none", false, 2, 8, 8, 2, 8),
];

export const demoActivityNotes: ActivityNote[] = [
  activityNote(
    "2026-06-22",
    "run",
    32,
    "easy",
    "Fake easy run with relaxed effort.",
    "Demo shoes",
    "Water before and after.",
  ),
  activityNote(
    "2026-06-23",
    "walk",
    30,
    "easy",
    "Fake recovery walk.",
    "Walking shoes",
    "Normal meals.",
  ),
  activityNote(
    "2026-06-25",
    "weights",
    25,
    "moderate",
    "Fake light strength session.",
    "Gym shoes",
    "Water.",
  ),
  activityNote(
    "2026-06-26",
    "run",
    42,
    "easy",
    "Fake longer easy run.",
    "Demo shoes",
    "Water and a small snack.",
  ),
  activityNote(
    "2026-06-27",
    "mobility",
    20,
    "easy",
    "Fake mobility routine.",
    "Mat",
    "Water.",
  ),
];

export const demoManualActivities: ManualActivity[] = [
  activity(
    "2026-06-22",
    "run",
    3.1,
    32,
    "10:19",
    120,
    142,
    158,
    4200,
    "Fake easy run.",
  ),
  activity(
    "2026-06-23",
    "walk",
    1.6,
    30,
    "18:45",
    40,
    null,
    null,
    3600,
    "Fake recovery walk.",
  ),
  activity(
    "2026-06-24",
    "rock_climbing",
    null,
    60,
    null,
    null,
    null,
    null,
    null,
    "Fake indoor climbing session.",
  ),
  activity(
    "2026-06-25",
    "weights",
    null,
    25,
    null,
    null,
    null,
    null,
    null,
    "Fake light strength session.",
  ),
  activity(
    "2026-06-26",
    "run",
    4.2,
    42,
    "10:00",
    180,
    146,
    162,
    5600,
    "Fake longer easy run.",
  ),
  activity(
    "2026-06-27",
    "walk",
    2.0,
    38,
    "19:00",
    60,
    null,
    null,
    4300,
    "Fake relaxed walk.",
  ),
  activity(
    "2026-06-27",
    "mobility",
    null,
    20,
    null,
    null,
    null,
    null,
    null,
    "Fake mobility work.",
  ),
  activity(
    "2026-06-28",
    "rest",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Fake rest day.",
  ),
];

export const demoPlanNotes =
  "Fake plan note: keep easy days easy, separate walking from running mileage, and hold effort conservative if calf tightness increases.";

function dailyNote(
  date: string,
  totalSteps: number,
  legSoreness: number,
  pain: number,
  painLocation: string,
  painType: string,
  gaitChanged: boolean,
  fatigue: number,
  energy: number,
  sleepQuality: number,
  stress: number,
  motivation: number,
): DailyNote {
  return {
    date,
    totalSteps,
    legSoreness,
    pain,
    painLocation,
    painType,
    gaitChanged,
    fatigue,
    energy,
    sleepQuality,
    stress,
    motivation,
    notes: "Fake public demo recovery note.",
  };
}

function activityNote(
  date: string,
  activityType: string,
  durationMinutes: number,
  intensity: string,
  details: string,
  gear: string,
  fuelingHydrationNotes: string,
): ActivityNote {
  return {
    date,
    activityType,
    durationMinutes,
    intensity,
    details,
    sorenessBefore: 1,
    sorenessAfter: 2,
    nextMorningSoreness: 2,
    painNotes: "No concerning fake pain note.",
    gear,
    fuelingHydrationNotes,
  };
}

function activity(
  date: string,
  activityType: string,
  distanceMiles: number | null,
  durationMinutes: number | null,
  paceMinPerMile: string | null,
  elevationFt: number | null,
  avgHr: number | null,
  maxHr: number | null,
  steps: number | null,
  notes: string,
): ManualActivity {
  return {
    date,
    source: "manual",
    activityType,
    distanceMiles,
    durationMinutes,
    paceMinPerMile,
    elevationFt,
    avgHr,
    maxHr,
    steps,
    notes,
  };
}
